### PR TITLE
CRUD Operations B2 - PUT and Controllers

### PR DESCRIPTION
**Pull request by YicongYan**
Add PUT endpoint to Course Controller.

### CODE REVIEW

**Review by erica-ll — APPROVED** [review]
LGTM! Tested locally and works fine

**Review by bella-ward — DISMISSED** [review]
LGTM. Nice tests.

**Review by pconrad — DISMISSED** [review]
LGTM

**Review by HououinKyouma-2036 — APPROVED** [review]
LGTM!!!
Nice job bro!

**Pull request merged**
