### PR TITLE
CRUD Operations B2 - DELETE and Controllers

### PR DESCRIPTION
**Pull request by YicongYan**
Add DELETE endpoint to CourseController

### CODE REVIEW

**Review by pconrad — APPROVED** [review]
LGTM

**Review by erica-ll — COMMENTED** [review]
LGTM. Delete works when pulled and tested locally

**Review by bella-ward — DISMISSED** [review]
Code LGTM.

**Review by HououinKyouma-2036 — APPROVED** [review]
Tested locally and the code works well! 
LGTM!!!

**Review by pconrad — DISMISSED** [review]
LGTM

**Pull request merged**
